name: Auto Close PR After 2 Minutes


on:
  pull_request:
    types: [opened]  # Trigger immediately upon PR creation

jobs:
  auto-close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 2 minutes
        run: sleep 120  # Wait for 2 minutes (120 seconds)

      - name: Close the PR
        if: github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          gh pr close $pr_number -c "Auto-closing PR after 2 minutes of creation."
